version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    hostname: redis
    networks:
    - machine_learning_network

  modelserver:
    image: afolabiabass/modelserver
    build:
      context: .
      dockerfile: ./docker/model.docker
    depends_on:
    - redis
    networks:
    - machine_learning_network
    env_file:
    - .env
    environment:
    - SERVER_SLEEP=0.25
    - BATCH_SIZE=32
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == worker

  webserver:
    image: afolabiabass/webserver
    build:
      context: .
      dockerfile: ./docker/web.docker
    ports:
    - "80:8000"
    networks:
    - machine_learning_network
    depends_on:
    - redis
    env_file:
    - .env
    environment:
    - CLIENT_SLEEP=0.25  # Time in ms between each poll by web server against Redis
    - CLIENT_MAX_TRIES=100  # Num tries by web server to retrieve results from Redis before giving up
    deploy:
      placement:
        constraints:
        - node.role == manager

networks:
    machine_learning_network:
